services:
  spring-application-template:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/application-db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      grafana:
        condition: service_started
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: application-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
  grafana:
    image: grafana/otel-lgtm
    ports:
      - 4317:4317
      - 4318:4318
      - 3000:3000