name: CI CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLICATION_NAME: spring-application-template

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Verify and package application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify -Pcoverage org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Upload JAR file artifact
        uses: actions/upload-artifact@v4
        with:
          path: target/*.jar
          name: ${{ env.APPLICATION_NAME }}
          if-no-files-found: error
  build-and-push:
    name: Build and Push Image
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR file artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Generate metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APPLICATION_NAME }}
          tags: type=raw,value=${{ github.event.pull_request.head.sha || github.sha }}
        id: docker_meta
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: JAR_FILE=*.jar
  deploy-image:
    name: Deploy Application
    needs: [ build-and-push ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup deploy env
        run: echo "Use this step to deploy your app if needed"